services:
  db:
    image: postgres
    container_name: local-pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadnim4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.pl
      PGADMIN_DEFAULT_PASSWORD: admin

