INSERT INTO artist (name) VALUES
('Taylor Swift'),
('Adele'),
('Dua Lipa'),
('Bob Dylan'),
('Lana Del Rey'),
('Ed Sheeran'),
('Billie Eilish'),
('Drake'),
('Kanye West'),
('Post Malone'),
('Cardi B'),
('The Weeknd'),
('Lady Gaga'),
('Kendrick Lamar'),
('Bruno Mars'),
('Katy Perry'),
('Rihanna'),
('Travis Scott'),
('Sia'),
('Beyoncé'),
('Ariana Grande'),
('Justin Bieber'),
('J Cole'),
('Kanye West'),
('Sam Smith'),
('Halsey'),
('Shawn Mendes'),
('Imagine Dragons'),
('Selena Gomez'),
('Miley Cyrus');
